name: Uppfæra matseðil

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Sækja Excel skjal
        run: |
          curl -L "https://imatehf-my.sharepoint.com/:x:/g/personal/john_imatehf_onmicrosoft_com/IQCz7R6QwKi1SLUSozx77SP3ATfXbZzJcwVkPEzQGR7C4aw?e=1nu9CT&download=1" -o "Matarstund matseðill.xlsx"

      - name: Vista á GitHub
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add "Matarstund matseðill.xlsx"
          git diff --staged --quiet || git commit -m "Uppfæra matseðil"
          git push
